from snakemake.utils import min_version

##### set minimum snakemake version #####

min_version("6.4.1")


##### setup config and necessary parameters #####


configfile: "config/config.yaml"


##### Impute potentially missing config parameters


if "fc_genes_extra" not in config:
    config["fc_genes_extra"] = "--primary"


if "fc_exons_extra" not in config:
    config["fc_exons_extra"] = "--nonOverlap 5 --primary"


##### setup report #####


report: "report/workflow.rst"


##### setup singularity #####


# this container defines the underlying OS for each job when using the workflow
# with --use-conda --use-singularity
container: "docker://continuumio/miniconda3"


##### load rules #####

if config["bam2bakr"]:

    include: "rules/common.smk"
    include: "rules/bam2bakr.smk"

else:

    include: "rules/common.smk"
    include: "rules/alignment.smk"
    include: "rules/bam2bakr.smk"


include: "rules/features.smk"


##### target rules #####


rule all:
    input:
        "results/cB/cB.csv.gz",
        expand(
            "results/tracks/{sample}.{mut}.{id}.{strand}.tdf",
            sample=SAMP_NAMES,
            mut=Mutation_Types,
            id=[0, 1, 2, 3, 4, 5],
            strand=["pos", "min"],
        ),
