from snakemake.utils import min_version

##### set minimum snakemake version #####

min_version("6.4.1")


##### setup config and necessary parameters #####


configfile: "config/config.yaml"


##### setup report #####


report: "report/workflow.rst"


##### setup singularity #####


# this container defines the underlying OS for each job when using the workflow
# with --use-conda --use-singularity
container: "docker://continuumio/miniconda3"


##### load rules #####


include: "rules/bam2bakr.smk"


##### target rules #####

rule all:
    input:
        "results/cB/cB.csv.gz",
        expand("results/tracks/{S_ID}_success.txt", S_ID=SAMP_NAMES)
        #expand("results/counts/{S_ID}_counts.csv.gz", S_ID=SAMP_NAMES)