
######## Parameters you MUST set #########

# location of ALL (including -s4U control) bam files
samples:
  KO_1: data/samples/KO_1.sorted.bam
  KO_ctl: data/samples/KO_ctl.sorted.bam
  WT_1: data/samples/WT_1.sorted.bam
  WT_2: data/samples/WT_2.sorted.bam

# sample IDs of -s4U control bam files (or leave blank if you have none)
# Needs to be same sample ID(s) that show up under samples entry
control_samples: ["KO_ctl"]


# location of annotation gtf file
annotation: data/annotation/GRCh38.gtf

# location of genome fasta file
genome_fasta: data/genome/GRCh38.fasta

######## Parameters you should probably double check ########

# Number of cpus to be used by pieline
cpus: 20

# Format of reads
FORMAT: "PE" # (PE, SE)
                    # [SE - single end reads]

# Strandedness of reads
strandedness: "R" # (F, R); F means read 1 represents original RNA sequence (vs. its reverse complement).

# Are you using the Windows subsystem for linux? 0 = Yes, 1 = No
WSL: 1

# Number of reads per fragment when splitting up bam file
fragment_size: 5000


# Type of mutations of interest
mut_tracks: "TC" # ("TC", "GA", "TC,GA")

# whether to make .tdf files or not
make_tracks: True

# Minimum base quality to call mutation
minqual: 40

# Which columns to keep in final cB.csv.gz file
keepcols: "sample,sj,io,ei,ai,GF,XF,rname"

# String common to spike-in gene_ids in annotation gtf
  # If you have no spike-ins, then this should be "\"\"", i.e., a string containing ""
spikename: "\"\""

# If True, tracks will be normalized
normalize: True

######## Parameters you should NEVER alter ########
awkscript: workflow/scripts/fragment_sam.awk
mutcall: workflow/scripts/mut_call.py
mutcnt: workflow/scripts/count_triple.py
count2tracks: workflow/scripts/count_to_tracks.py
