##### Parameters you will likely have to change #####

# Run bam2bakR only? If true, will expect paths to bam files as input and alignment steps will be skipped. If false,
# paths to directories containing fastq files will be expected as input.
bam2bakr: True

# path to directory containing fastq files if bam2bakr is False
# path to bam files if bam2bakr is True
## example of what samples could look like for bam input
samples:
  WT_1: data/bam/WT_replicate_1.bam
  WT_2: data/bam/WT_replicate_2.bam
  WT_ctl: data/bam/WT_nos4U.bam
  KO_1: data/bam/KO_replicate_1.bam
  KO_2: data/bam/KO_replicate_2.bam
  KO_ctl: data/bam/KO_nos4U.bam


## example of what samples will look like for fastq input
# samples:
#   WT_1: data/fastq/WT_1
#   WT_2: data/fastq/WT_2
#   WT_ctl: data/fastq/WT_ctl
#   KO_1: data/fastq/KO_1
#   KO_2: data/fastq/KO_2
#   KO_ctl: data/fastq/KO_ctl

# location of annotation gtf file
annotation: data/annotation/GRCh38.gtf

# location of flattened annotation (will be created by pipeline if it does not already exist)
flat_annotation: data/annotation/GRCh38_flat.gtf

# -s4U control sample IDs
control_samples: ['WT_ctl', 'KO_ctl']

# location of genome fasta file
genome_fasta: data/genome/GRCh38.fa

# If using STAR, do you want to note all of the transcripts a read aligned to in the final cB?
transcripts_cB: True


##### Parameters that are always relevant #####

# Format of reads
FORMAT: "PE" # (PE, SE, NU)
                    # [SE - single end reads]
                    # [NU - including non-unique] (not tested)


# Strandedness of reads
strandedness: "R" # (F, R); F means read 1 represents original RNA sequence (vs. its reverse complement).


# Type of browser tracks to generate
mut_tracks: "TC" # ("TC", "GA", "TC,GA")

# Minimum base quality to call mutation
minqual: 40

# Which columns to keep in final cB.csv.gz file 
# Don't include mut_tracks and the relevant nX, where X denotes either T (for TC mutations) or G (for GA mutations). These are always included
keepcols: "sample,sj,io,ei,ai,GF,XF,rname"

# String common to spike-in gene_ids in annotation gtf
  # If you have no spike-ins, then this should be "\"\"", i.e., an empty string ("")
spikename: "\"\""

# If True, tracks will be normalized
normalize: True

# Are you using the Windows subsystem for linux? 0 = Yes, 1 = No
WSL: 1

# Are there jI and jM tags in your bam file?
remove_tags: False


##### Parameters that are only relevant if bam2bakr is False #####

# location of hisat2 indices (directory containing indices)
HISAT2: data/hisat2/grch38_tran/

# location of hisat3n indices (path to and common prefix of all .ht2 files)
HISAT_3N: data/hisat_3n/GRCh38

# location of STAR indices
STAR_index: data/star/

# If TRUE, hisat-3n will be used for alignment
use_hisat3n: False

# If TRUE STAR will be used for alignment;  if hisat-3n is also TRUE, hisat-3n will be used and not STAR
use_star: False

# If TRUE, index will be built for star and directory will be created at path set in STAR_index parameter
build_star: False

# If use_hisat3n TRUE, then this specifies path to hisat_3n executable
hisat3n_path: hisat-3n
  # If hisat-3n is on your PATH, this will just be hisat-3n

# Add a 'chr' to each chromosome number during alignment. [Useful when aliner index is number-based, but GTF annotation is chr-based]
chr_tag: True

# Are you on Yale's HPC where hisat-3n can be loaded as a module using Lmod system?
Yale: False

# Are you using a flattened annotation from FlatStacks?
flattened: False

# code specifying adapters to be trimmed that will be passed to cutadapt
adapter: "-a AGATCGGAAGAGC -A AGATCGGAAGAGC"

# Optional code to pass to cutadapt
cutadapt_extra: "--minimum-length 20"
  # No additional parameters are passed, so this can include any of cutadapt's optional parameters

# Extra parameters to be passed to STAR
star_extra: "--outFilterMismatchNmax 20"
  # Already passing: "--outSAMtype BAM SortedByCoordinate --outSAMattributes NH HI AS NM MD --quantMode TranscriptomeSAM GeneCounts --sjdbGTFfile config["annotation"]
  # Including any of the already set parameters will yield an error.

# Extra parameters to be passed to Hisat2
hisat2_extra: "--mp 1,0"
  # No additional parameters are passed, so this can include any of hisat2's optional parameters

# Extra parameters to be passed to RSEM
rsem_extra: ""


# Number of lines to split csv into when sorting it
  # Each chunk is sorted independently and then merged
  # to limit RAM usage for sorting large table
chunk_size: 25000

##### PARAMETERS THAT ONLY MATTER IF USING FASTQ2BAKR AND STAR #####

pnews:
  WT_1: 0.05 
  WT_2: 0.05
  WT_ctl: 0
  KO_1: 0.05
  KO_2: 0.05
  KO_ctl: 0

polds:
  WT_1: 0.001
  WT_2: 0.001
  WT_ctl: 0
  KO_1: 0.001
  KO_2: 0.001
  KO_ctl: 0