name: Tests

on:
  push:
    branches:
      - main
      - featurecount
  pull_request:
    branches_ignore: []

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Linting
      uses: ezherman/snakemake-github-action@5027c0e706ada924ab91e0501bd92185fc98de3c
      with:
        directory: .test
        snakefile: workflow/Snakefile
        args: "--configfile .test/configs/star_config.yaml --lint"

  run-workflow:
    runs-on: ubuntu-latest
    needs:
      - linting
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Test workflow (star)
      uses: ezherman/snakemake-github-action@5027c0e706ada924ab91e0501bd92185fc98de3c
      with:
        directory: .test
        snakefile: workflow/Snakefile
        args: "--configfile .test/configs/star_config.yaml --use-conda --show-failed-logs --cores 2 --conda-cleanup-pkgs cache"